Update online-boutique YAMLs
Summary: Previous releases of online-boutique were removed, so we are updating to the latest image versions.

Test Plan: Deployed the YAMLs to a px-online-boutique namespace and check that everything starts up

Reviewers: yzhao, htroisi, nserrino, vihang

Reviewed By: vihang

Signed-off-by: Michelle Nguyen <michellenguyen@pixielabs.ai>

Differential Revision: https://phab.corp.pixielabs.ai/D10719

GitOrigin-RevId: ecac2909e0007df242635d6d990224d7c67a586b

diff --git a/demos/online-boutique/online-boutique.yaml b/demos/online-boutique/online-boutique.yaml
--- a/demos/online-boutique/online-boutique.yaml
+++ b/demos/online-boutique/online-boutique.yaml
@@ -16,7 +16,7 @@ spec:
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/emailservice:v0.2.2
+        image: gcr.io/google-samples/microservices-demo/emailservice:v0.3.6
         ports:
         - containerPort: 8080
         env:
@@ -24,8 +24,8 @@ spec:
           value: "8080"
         # - name: DISABLE_TRACING
         #   value: "1"
-        - name: DISABLE_PROFILER
-          value: "1"
+        # - name: DISABLE_PROFILER
+        #   value: "1"
         readinessProbe:
           periodSeconds: 5
           exec:
@@ -71,7 +71,7 @@ spec:
       serviceAccountName: default
       containers:
         - name: server
-          image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.2.2
+          image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.3.6
           ports:
           - containerPort: 5050
           readinessProbe:
@@ -141,7 +141,7 @@ spec:
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.2.2
+        image: gcr.io/google-samples/microservices-demo/recommendationservice:v0.3.6
         ports:
         - containerPort: 8080
         readinessProbe:
@@ -202,7 +202,7 @@ spec:
       serviceAccountName: default
       containers:
         - name: server
-          image: gcr.io/google-samples/microservices-demo/frontend:v0.2.2
+          image: gcr.io/google-samples/microservices-demo/frontend:v0.3.6
           ports:
           - containerPort: 8080
           readinessProbe:
@@ -238,14 +238,18 @@ spec:
             value: "checkoutservice:5050"
           - name: AD_SERVICE_ADDR
             value: "adservice:9555"
-          - name: ENV_PLATFORM
-            value: "gcp"
+          # # ENV_PLATFORM: One of: local, gcp, aws, azure, onprem, alibaba
+          # # When not set, defaults to "local" unless running in GKE, otherwies auto-sets to gcp
+          # - name: ENV_PLATFORM
+          #   value: "aws"
           # - name: DISABLE_TRACING
           #   value: "1"
           # - name: DISABLE_PROFILER
           #   value: "1"
           # - name: JAEGER_SERVICE_ADDR
           #   value: "jaeger-collector:14268"
+          # - name: CYMBAL_BRANDING
+          #   value: "true"
           resources:
             requests:
               cpu: 100m
@@ -297,12 +301,18 @@ spec:
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.2.2
+        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.3.6
         ports:
         - containerPort: 50051
         env:
         - name: PORT
           value: "50051"
+        # - name: DISABLE_TRACING
+        #   value: "1"
+        # - name: DISABLE_PROFILER
+        #   value: "1"
+        # - name: DISABLE_DEBUGGER
+        #   value: "1"
         readinessProbe:
           exec:
             command: ["/bin/grpc_health_probe", "-addr=:50051"]
@@ -347,7 +357,7 @@ spec:
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/pixie-prod/demos/microservices-demo-app/productcatalogservice:profilerdemo
+        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.3.6
         ports:
         - containerPort: 3550
         env:
@@ -405,7 +415,7 @@ spec:
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/cartservice:v0.2.2
+        image: gcr.io/google-samples/microservices-demo/cartservice:v0.3.6
         ports:
         - containerPort: 7070
         env:
@@ -460,14 +470,30 @@ spec:
       serviceAccountName: default
       terminationGracePeriodSeconds: 5
       restartPolicy: Always
+      initContainers:
+      - command:
+        - /bin/sh
+        - -exc
+        - |
+          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
+          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+          if test $STATUSCODE -ne 200; then
+              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+              exit 1
+          fi
+        name: frontend-check
+        image: busybox:latest
+        env:
+        - name: FRONTEND_ADDR
+          value: "frontend:80"
       containers:
       - name: main
-        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.2.2
+        image: gcr.io/google-samples/microservices-demo/loadgenerator:v0.3.6
         env:
         - name: FRONTEND_ADDR
           value: "frontend:80"
         - name: USERS
-          value: "100"
+          value: "10"
         resources:
           requests:
             cpu: 300m
@@ -493,7 +519,7 @@ spec:
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.2.2
+        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.3.6
         ports:
         - name: grpc
           containerPort: 7000
@@ -549,7 +575,7 @@ spec:
       serviceAccountName: default
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.2.2
+        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.3.6
         ports:
         - containerPort: 50051
         env:
@@ -661,7 +687,7 @@ spec:
       terminationGracePeriodSeconds: 5
       containers:
       - name: server
-        image: gcr.io/google-samples/microservices-demo/adservice:v0.2.2
+        image: gcr.io/google-samples/microservices-demo/adservice:v0.3.6
         ports:
         - containerPort: 9555
         env:
@@ -671,8 +697,8 @@ spec:
         #   value: "1"
         # - name: DISABLE_TRACING
         #   value: "1"
-        #- name: JAEGER_SERVICE_ADDR
-        #  value: "jaeger-collector:14268"
+        # - name: JAEGER_SERVICE_ADDR
+        #   value: "jaeger-collector:14268"
         resources:
           requests:
             cpu: 200m
